# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tkrzw_rpc.proto for package 'tkrzw_rpc'
# Original file comments:
# Service definition of Tkrzw-RPC
#
# Copyright 2020 Google LLC
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain a copy of the License at
#     https://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.  See the License for the specific language governing permissions
# and limitations under the License.
#

require 'grpc'
require 'tkrzw_rpc_pb'

module TkrzwRpc
  module DBMService
    # Definition of the database service.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tkrzw_rpc.DBMService'

      rpc :Echo, ::TkrzwRpc::EchoRequest, ::TkrzwRpc::EchoResponse
      rpc :Inspect, ::TkrzwRpc::InspectRequest, ::TkrzwRpc::InspectResponse
      rpc :Get, ::TkrzwRpc::GetRequest, ::TkrzwRpc::GetResponse
      rpc :GetMulti, ::TkrzwRpc::GetMultiRequest, ::TkrzwRpc::GetMultiResponse
      rpc :Set, ::TkrzwRpc::SetRequest, ::TkrzwRpc::SetResponse
      rpc :SetMulti, ::TkrzwRpc::SetMultiRequest, ::TkrzwRpc::SetMultiResponse
      rpc :Remove, ::TkrzwRpc::RemoveRequest, ::TkrzwRpc::RemoveResponse
      rpc :RemoveMulti, ::TkrzwRpc::RemoveMultiRequest, ::TkrzwRpc::RemoveMultiResponse
      rpc :Append, ::TkrzwRpc::AppendRequest, ::TkrzwRpc::AppendResponse
      rpc :AppendMulti, ::TkrzwRpc::AppendMultiRequest, ::TkrzwRpc::AppendMultiResponse
      rpc :CompareExchange, ::TkrzwRpc::CompareExchangeRequest, ::TkrzwRpc::CompareExchangeResponse
      rpc :Increment, ::TkrzwRpc::IncrementRequest, ::TkrzwRpc::IncrementResponse
      rpc :CompareExchangeMulti, ::TkrzwRpc::CompareExchangeMultiRequest, ::TkrzwRpc::CompareExchangeMultiResponse
      rpc :Count, ::TkrzwRpc::CountRequest, ::TkrzwRpc::CountResponse
      rpc :GetFileSize, ::TkrzwRpc::GetFileSizeRequest, ::TkrzwRpc::GetFileSizeResponse
      rpc :Clear, ::TkrzwRpc::ClearRequest, ::TkrzwRpc::ClearResponse
      rpc :Rebuild, ::TkrzwRpc::RebuildRequest, ::TkrzwRpc::RebuildResponse
      rpc :ShouldBeRebuilt, ::TkrzwRpc::ShouldBeRebuiltRequest, ::TkrzwRpc::ShouldBeRebuiltResponse
      rpc :Synchronize, ::TkrzwRpc::SynchronizeRequest, ::TkrzwRpc::SynchronizeResponse
      rpc :Search, ::TkrzwRpc::SearchRequest, ::TkrzwRpc::SearchResponse
      rpc :Stream, stream(::TkrzwRpc::StreamRequest), stream(::TkrzwRpc::StreamResponse)
      rpc :Iterate, stream(::TkrzwRpc::IterateRequest), stream(::TkrzwRpc::IterateResponse)
      rpc :Replicate, ::TkrzwRpc::ReplicateRequest, stream(::TkrzwRpc::ReplicateResponse)
      rpc :ChangeMaster, ::TkrzwRpc::ChangeMasterRequest, ::TkrzwRpc::ChangeMasterResponse
    end

    Stub = Service.rpc_stub_class
  end
end
