# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tkrzw_rpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tkrzw_rpc.proto", :syntax => :proto3) do
    add_message "tkrzw_rpc.StatusProto" do
      optional :code, :int32, 1
      optional :message, :string, 2
    end
    add_message "tkrzw_rpc.StringPair" do
      optional :first, :string, 1
      optional :second, :string, 2
    end
    add_message "tkrzw_rpc.BytesPair" do
      optional :first, :bytes, 1
      optional :second, :bytes, 2
    end
    add_message "tkrzw_rpc.RecordState" do
      optional :existence, :bool, 1
      optional :key, :bytes, 2
      optional :value, :bytes, 3
    end
    add_message "tkrzw_rpc.EchoRequest" do
      optional :message, :string, 1
    end
    add_message "tkrzw_rpc.EchoResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :echo, :string, 2
    end
    add_message "tkrzw_rpc.InspectRequest" do
      optional :dbm_index, :int32, 1
    end
    add_message "tkrzw_rpc.InspectResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      repeated :records, :message, 2, "tkrzw_rpc.StringPair"
    end
    add_message "tkrzw_rpc.GetRequest" do
      optional :dbm_index, :int32, 1
      optional :key, :bytes, 2
      optional :omit_value, :bool, 3
    end
    add_message "tkrzw_rpc.GetResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :value, :bytes, 2
    end
    add_message "tkrzw_rpc.GetMultiRequest" do
      optional :dbm_index, :int32, 1
      repeated :keys, :bytes, 2
    end
    add_message "tkrzw_rpc.GetMultiResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      repeated :records, :message, 2, "tkrzw_rpc.BytesPair"
    end
    add_message "tkrzw_rpc.SetRequest" do
      optional :dbm_index, :int32, 1
      optional :key, :bytes, 2
      optional :value, :bytes, 3
      optional :overwrite, :bool, 4
    end
    add_message "tkrzw_rpc.SetResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.SetMultiRequest" do
      optional :dbm_index, :int32, 1
      repeated :records, :message, 2, "tkrzw_rpc.BytesPair"
      optional :overwrite, :bool, 3
    end
    add_message "tkrzw_rpc.SetMultiResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.RemoveRequest" do
      optional :dbm_index, :int32, 1
      optional :key, :bytes, 2
    end
    add_message "tkrzw_rpc.RemoveResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.RemoveMultiRequest" do
      optional :dbm_index, :int32, 1
      repeated :keys, :bytes, 2
    end
    add_message "tkrzw_rpc.RemoveMultiResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.AppendRequest" do
      optional :dbm_index, :int32, 1
      optional :key, :bytes, 2
      optional :value, :bytes, 3
      optional :delim, :bytes, 4
    end
    add_message "tkrzw_rpc.AppendResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.AppendMultiRequest" do
      optional :dbm_index, :int32, 1
      repeated :records, :message, 2, "tkrzw_rpc.BytesPair"
      optional :delim, :bytes, 3
    end
    add_message "tkrzw_rpc.AppendMultiResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.CompareExchangeRequest" do
      optional :dbm_index, :int32, 1
      optional :key, :bytes, 2
      optional :expected_existence, :bool, 3
      optional :expected_value, :bytes, 4
      optional :desired_existence, :bool, 5
      optional :desired_value, :bytes, 6
    end
    add_message "tkrzw_rpc.CompareExchangeResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.IncrementRequest" do
      optional :dbm_index, :int32, 1
      optional :key, :bytes, 2
      optional :increment, :int64, 3
      optional :initial, :int64, 4
    end
    add_message "tkrzw_rpc.IncrementResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :current, :int64, 2
    end
    add_message "tkrzw_rpc.CompareExchangeMultiRequest" do
      optional :dbm_index, :int32, 1
      repeated :expected, :message, 2, "tkrzw_rpc.RecordState"
      repeated :desired, :message, 3, "tkrzw_rpc.RecordState"
    end
    add_message "tkrzw_rpc.CompareExchangeMultiResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.RekeyRequest" do
      optional :dbm_index, :int32, 1
      optional :old_key, :bytes, 2
      optional :new_key, :bytes, 3
      optional :overwrite, :bool, 4
      optional :copying, :bool, 5
    end
    add_message "tkrzw_rpc.RekeyResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.PopFirstRequest" do
      optional :dbm_index, :int32, 1
      optional :omit_key, :bool, 2
      optional :omit_value, :bool, 3
      optional :retry_wait, :double, 4
    end
    add_message "tkrzw_rpc.PopFirstResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :key, :bytes, 2
      optional :value, :bytes, 3
    end
    add_message "tkrzw_rpc.PushLastRequest" do
      optional :dbm_index, :int32, 1
      optional :value, :bytes, 2
      optional :wtime, :double, 3
      optional :notify, :bool, 4
    end
    add_message "tkrzw_rpc.PushLastResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.CountRequest" do
      optional :dbm_index, :int32, 1
    end
    add_message "tkrzw_rpc.CountResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :count, :int64, 2
    end
    add_message "tkrzw_rpc.GetFileSizeRequest" do
      optional :dbm_index, :int32, 1
    end
    add_message "tkrzw_rpc.GetFileSizeResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :file_size, :int64, 2
    end
    add_message "tkrzw_rpc.ClearRequest" do
      optional :dbm_index, :int32, 1
    end
    add_message "tkrzw_rpc.ClearResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.RebuildRequest" do
      optional :dbm_index, :int32, 1
      repeated :params, :message, 2, "tkrzw_rpc.StringPair"
    end
    add_message "tkrzw_rpc.RebuildResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.ShouldBeRebuiltRequest" do
      optional :dbm_index, :int32, 1
    end
    add_message "tkrzw_rpc.ShouldBeRebuiltResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :tobe, :bool, 2
    end
    add_message "tkrzw_rpc.SynchronizeRequest" do
      optional :dbm_index, :int32, 1
      optional :hard, :bool, 2
      repeated :params, :message, 3, "tkrzw_rpc.StringPair"
    end
    add_message "tkrzw_rpc.SynchronizeResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
    add_message "tkrzw_rpc.SearchRequest" do
      optional :dbm_index, :int32, 1
      optional :mode, :string, 2
      optional :pattern, :bytes, 3
      optional :capacity, :int32, 4
    end
    add_message "tkrzw_rpc.SearchResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      repeated :matched, :bytes, 2
    end
    add_message "tkrzw_rpc.StreamRequest" do
      optional :omit_response, :bool, 101
      oneof :request_oneof do
        optional :echo_request, :message, 1, "tkrzw_rpc.EchoRequest"
        optional :get_request, :message, 2, "tkrzw_rpc.GetRequest"
        optional :set_request, :message, 3, "tkrzw_rpc.SetRequest"
        optional :remove_request, :message, 4, "tkrzw_rpc.RemoveRequest"
        optional :append_request, :message, 5, "tkrzw_rpc.AppendRequest"
        optional :compare_exchange_request, :message, 6, "tkrzw_rpc.CompareExchangeRequest"
        optional :increment_request, :message, 7, "tkrzw_rpc.IncrementRequest"
      end
    end
    add_message "tkrzw_rpc.StreamResponse" do
      oneof :response_oneof do
        optional :echo_response, :message, 1, "tkrzw_rpc.EchoResponse"
        optional :get_response, :message, 2, "tkrzw_rpc.GetResponse"
        optional :set_response, :message, 3, "tkrzw_rpc.SetResponse"
        optional :remove_response, :message, 4, "tkrzw_rpc.RemoveResponse"
        optional :append_response, :message, 5, "tkrzw_rpc.AppendResponse"
        optional :compare_exchange_response, :message, 6, "tkrzw_rpc.CompareExchangeResponse"
        optional :increment_response, :message, 7, "tkrzw_rpc.IncrementResponse"
      end
    end
    add_message "tkrzw_rpc.IterateRequest" do
      optional :dbm_index, :int32, 1
      optional :operation, :enum, 2, "tkrzw_rpc.IterateRequest.OpType"
      optional :key, :bytes, 3
      optional :value, :bytes, 4
      optional :jump_inclusive, :bool, 5
      optional :omit_key, :bool, 6
      optional :omit_value, :bool, 7
    end
    add_enum "tkrzw_rpc.IterateRequest.OpType" do
      value :OP_NONE, 0
      value :OP_FIRST, 1
      value :OP_LAST, 2
      value :OP_JUMP, 3
      value :OP_JUMP_LOWER, 4
      value :OP_JUMP_UPPER, 5
      value :OP_NEXT, 6
      value :OP_PREVIOUS, 7
      value :OP_GET, 8
      value :OP_SET, 9
      value :OP_REMOVE, 10
      value :OP_STEP, 11
    end
    add_message "tkrzw_rpc.IterateResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :key, :bytes, 2
      optional :value, :bytes, 3
    end
    add_message "tkrzw_rpc.ReplicateRequest" do
      optional :min_timestamp, :int64, 1
      optional :server_id, :int32, 2
      optional :wait_time, :double, 3
    end
    add_message "tkrzw_rpc.ReplicateResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
      optional :timestamp, :int64, 2
      optional :server_id, :int32, 3
      optional :dbm_index, :int32, 4
      optional :op_type, :enum, 5, "tkrzw_rpc.ReplicateResponse.OpType"
      optional :key, :bytes, 6
      optional :value, :bytes, 7
    end
    add_enum "tkrzw_rpc.ReplicateResponse.OpType" do
      value :OP_NOOP, 0
      value :OP_SET, 1
      value :OP_REMOVE, 2
      value :OP_CLEAR, 3
    end
    add_message "tkrzw_rpc.ChangeMasterRequest" do
      optional :master, :string, 1
      optional :timestamp_skew, :int64, 2
    end
    add_message "tkrzw_rpc.ChangeMasterResponse" do
      optional :status, :message, 1, "tkrzw_rpc.StatusProto"
    end
  end
end

module TkrzwRPC
  StatusProto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.StatusProto").msgclass
  StringPair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.StringPair").msgclass
  BytesPair = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.BytesPair").msgclass
  RecordState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RecordState").msgclass
  EchoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.EchoRequest").msgclass
  EchoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.EchoResponse").msgclass
  InspectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.InspectRequest").msgclass
  InspectResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.InspectResponse").msgclass
  GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.GetRequest").msgclass
  GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.GetResponse").msgclass
  GetMultiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.GetMultiRequest").msgclass
  GetMultiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.GetMultiResponse").msgclass
  SetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SetRequest").msgclass
  SetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SetResponse").msgclass
  SetMultiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SetMultiRequest").msgclass
  SetMultiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SetMultiResponse").msgclass
  RemoveRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RemoveRequest").msgclass
  RemoveResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RemoveResponse").msgclass
  RemoveMultiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RemoveMultiRequest").msgclass
  RemoveMultiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RemoveMultiResponse").msgclass
  AppendRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.AppendRequest").msgclass
  AppendResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.AppendResponse").msgclass
  AppendMultiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.AppendMultiRequest").msgclass
  AppendMultiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.AppendMultiResponse").msgclass
  CompareExchangeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.CompareExchangeRequest").msgclass
  CompareExchangeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.CompareExchangeResponse").msgclass
  IncrementRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.IncrementRequest").msgclass
  IncrementResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.IncrementResponse").msgclass
  CompareExchangeMultiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.CompareExchangeMultiRequest").msgclass
  CompareExchangeMultiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.CompareExchangeMultiResponse").msgclass
  RekeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RekeyRequest").msgclass
  RekeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RekeyResponse").msgclass
  PopFirstRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.PopFirstRequest").msgclass
  PopFirstResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.PopFirstResponse").msgclass
  PushLastRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.PushLastRequest").msgclass
  PushLastResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.PushLastResponse").msgclass
  CountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.CountRequest").msgclass
  CountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.CountResponse").msgclass
  GetFileSizeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.GetFileSizeRequest").msgclass
  GetFileSizeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.GetFileSizeResponse").msgclass
  ClearRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ClearRequest").msgclass
  ClearResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ClearResponse").msgclass
  RebuildRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RebuildRequest").msgclass
  RebuildResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.RebuildResponse").msgclass
  ShouldBeRebuiltRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ShouldBeRebuiltRequest").msgclass
  ShouldBeRebuiltResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ShouldBeRebuiltResponse").msgclass
  SynchronizeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SynchronizeRequest").msgclass
  SynchronizeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SynchronizeResponse").msgclass
  SearchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SearchRequest").msgclass
  SearchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.SearchResponse").msgclass
  StreamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.StreamRequest").msgclass
  StreamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.StreamResponse").msgclass
  IterateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.IterateRequest").msgclass
  IterateRequest::OpType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.IterateRequest.OpType").enummodule
  IterateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.IterateResponse").msgclass
  ReplicateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ReplicateRequest").msgclass
  ReplicateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ReplicateResponse").msgclass
  ReplicateResponse::OpType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ReplicateResponse.OpType").enummodule
  ChangeMasterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ChangeMasterRequest").msgclass
  ChangeMasterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tkrzw_rpc.ChangeMasterResponse").msgclass
end
